name: Build Daily Tech News

on:
  schedule:
    # Run daily at 03:10 UTC (06:10 Asia/Tehran)
    - cron: '10 3 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'templates/**'
      - '.github/workflows/**'

permissions:
  contents: write
  pages: write
  id-token: write
  contents: write  # Add write permission for contents

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run news aggregation
      run: |
        cd ${{ github.workspace }}
        python scripts/fetch_news.py
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git diff --staged --quiet || git commit -m "Daily news update $(date +'%Y-%m-%d')"
        git push origin main
      env:
